import type { NextPage } from "next";
import Head from "next/head";

import { Nav } from "../components/Nav";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Nav description="Home page: login / module options / modules index" />
  </div>
);

export default Home;
